on swap hand items:
	cancel event

on inventory click:
    if event-inventory is player's inventory:
        if clicked slot is 40:
            close player's inventory
            cancel event

options:
    GUI-Item-TopBal1: {_topbp}'s head named "&a&l&n%{_topbp}%" with lore "", "{@firstplace}", "", "{@currbal}:", "&2$&a%{_topb}%" and ""
    GUI-Item-TopBal1-Slot: 11
    GUI-Item-TopBal2: {_topbp}'s head named "&a&l&n%{_topbp}%" with lore "", "{@secondplace}", "", "{@currbal}:", "&2$&a%{_topb}%" and ""
    GUI-Item-TopBal2-Slot: 13
    GUI-Item-TopBal3: {_topbp}'s head named "&a&l&n%{_topbp}%" with lore "", "{@thirdplace}", "", "{@currbal}:", "&2$&a%{_topb}%" and ""
    GUI-Item-TopBal3-Slot: 15

command /season:
    trigger:
        #set {_1} to placeholder "vault_eco_top_player_1"
        #set {_1bal} to placeholder "vault_eco_top_balance_commas_1"
        #set {_1skull} to skull of {_1} parsed as an offline player
        #set {_2} to placeholder "vault_eco_top_player_2" 
        #set {_2bal} to placeholder "vault_eco_top_balance_commas_2"
        #set {_3} to placeholder "vault_eco_top_player_3" 
        #set {_3bal} to placeholder "vault_eco_top_balance_commas_3"
        tcurrentSeason(player)

function tcurrentSeason(p: player):
    open chest with 3 rows named "&b&lCurrent &3&lSeason" to {_p}
    format a gui slot 0, 2, 4, 6, 8, 18, 20, 24 and 26 of {_p} with light blue glass pane named "&8"
    format a gui slot 1, 3, 5, 7, 9, 17, 19, 21, 23, and 25 of {_p} with blue glass pane named "&8"
    set {_topb} to placeholder "vault_eco_top_balance_commas_1" from {_p}
    set {_topbp} to placeholder "vault_eco_top_player_1" from {_p}
    set {_topbp} to {_topbp} parsed as an offline player
    set slot {@GUI-Item-TopBal1-Slot} of {_p}'s current inventory to {@GUI-Item-TopBal1}    
    set {_topb} to placeholder "vault_eco_top_balance_commas_2" from {_p}
    set {_topbp} to placeholder "vault_eco_top_player_2" from {_p}
    set {_topbp} to {_topbp} parsed as an offline player
    set slot {@GUI-Item-TopBal2-Slot} of {_p}'s current inventory to {@GUI-Item-TopBal2}    
    set {_topb} to placeholder "vault_eco_top_balance_commas_3" from {_p}
    set {_topbp} to placeholder "vault_eco_top_player_3" from {_p}
    set {_topbp} to {_topbp} parsed as an offline player
    set slot {@GUI-Item-TopBal3-Slot} of {_p}'s current inventory to {@GUI-Item-TopBal3}
    format gui slot 22 of {_p} with glowing arrow named "&cBack" to run function payoutWinners({_p}, 0)
