on first join:
    if {rules.read::%UUID of player%} is not set:
        set {rules.read::%UUID of player%} to false

command /rulesreset:
    trigger:
        set {rules.read::%UUID of player%} to false

on any movement:
    if {rules.read::%UUID of player%} is false:
        cancel event
        send ""
        send "&b&lFast&3&lGens &8➤ &cPlease read &7&o/rules &cfirst."
        send ""

on command "/rules":
    wait 1 second 
    send ""
    send "&b&lFast&3&lGens &8➤ &cMake sure you have read all pages of &7&o/rules&c."
    send ""
    set {rules.read::%UUID of player%} to true

on chat:
    if {rules.read::%UUID of player%} is false:
        cancel event
        send ""
        send "&b&lFast&3&lGens &8➤ &cPlease read &7&o/rules &cfirst."
        send ""