on skript load:
    create a new mongo client to host "mongodb+srv://test:test@cluster0.adzx4.mongodb.net/Cluster0?retryWrites=true&w=majority" as "link"
    set {client.l} to client named "link"
    set {database.l} to mongo database named "mongosk" of {client.l}
    set {collection.l} to collection named "link" of {database.l}

command /database [<text>] [<text>]:
    trigger:
        TestLink(arg 1, arg 2)

function TestLink(u: text, d: text):
    set {_doc} to new mongo document
    set value "Minecraft Account" of {_doc} to "%{_u}%"          # MINECRAFT UUID
    set value "Discord Account" of {_doc} to "%{_d}%"    # DISCORD ID 
    save document {_doc} in {collection.l}